export const START_TIMER = 'START_TIMER'
export const STOP_TIMER = 'STOP_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
export const COUNTDOWN_TIMER = 'COUNTDOWN_TIMER'
export const SET_TIME = 'SET_TIME'
export const ADD_TOMATO = 'ADD_TOMATO'
